name: CI

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
            core.info('ref: ${{ github.ref }}, sha: ${{ github.sha }}')
            core.info(JSON.stringify('${{ toJSON(github) }}', null, 2))
